### ISSUE TITLE
Why did you crash? FEATURE

### ISSUE THREAD

**Issue by chrisparnin** [BotsBots/BugBot#19]
For debugging purposes, be able to print out tail of log files, etc. in order to get some useful info.
target completion: X
priority: HIGH

**Comment by ianmcxa** [comment]
I've got the log reporting crashes now automatically.

**Comment by chrisparnin** [comment]
How do you use/activate this feature?

**Comment by ianmcxa** [comment]
It's just a log file on the server. I just realized that this feature is making the log accessible.

**Comment by ianmcxa** [comment]
'show log' will now return the last 10 entries in the log file.
